### ISSUE TITLE
Did you rewrite history intentionally

### ISSUE THREAD

**Issue by tarsius** [etu/0blayout-mode#5]
It seems you have rewritten history at least twice and possibly unintentionally. The `master` branch in this repo, the `1.0.0` tag, and the older history I have mirrored [here](https://github.com/emacsmirror/0blayout) all have completely independent histories.

The history in the current `master` branch seems to be the worst. You have dropped all commits that did not happen directly on it but which where merged into it. Only the merge commits remain, but the commits which came with commit messages explaining why a change was made are gone.

**Comment by etu** [comment]
Yes, and also no.

I did rewrite it intentionally. It wasn't a mistake, but the plan didn't fall out as I planned. I was testing to sign git commits in history and thought it all was fine and pushed the new history. But I rolled it back based on the mirror and added changes made later. Then I also only signed the tag.

**Comment by etu** [comment]
@tarsius How often does the mirror get's updated? Just wondering?

**Comment by tarsius** [comment]
It varies. Once a week maybe, on average.
